# cloudflared tunnel create dbee-builder-dev

tunnel: e1435508-c15c-4731-a06d-ddda678b5aa0
credentials-file: /Users/yevhen/.cloudflared/e1435508-c15c-4731-a06d-ddda678b5aa0.json

ingress:
  - hostname: builder-dev.dbee.be
    service: http://localhost:5173
  - service: http_status:404
